export interface IngredientData {
  id: string
  name: string
  category: string
  calories: number // per 100g
  protein: number // per 100g
  carbs: number // per 100g
  fat: number // per 100g
  fiber: number // per 100g
  allergens: string[]
  unit: string
  inPantry?: boolean
  pantryAmount?: number
}

export const mockIngredients: IngredientData[] = [
  {
    id: "1",
    name: "Köttfärs (blandfärs)",
    category: "Kött",
    calories: 250,
    protein: 20,
    carbs: 0,
    fat: 18,
    fiber: 0,
    allergens: [],
    unit: "g",
    inPantry: true,
    pantryAmount: 500,
  },
  {
    id: "2",
    name: "Ägg",
    category: "Mejeri",
    calories: 155,
    protein: 13,
    carbs: 1,
    fat: 11,
    fiber: 0,
    allergens: ["Ägg"],
    unit: "st",
    inPantry: true,
    pantryAmount: 6,
  },
  {
    id: "3",
    name: "Vetemjöl",
    category: "Torrvaror",
    calories: 364,
    protein: 10,
    carbs: 76,
    fat: 1,
    fiber: 3,
    allergens: ["Gluten"],
    unit: "dl",
    inPantry: false,
  },
  {
    id: "4",
    name: "Mjölk",
    category: "Mejeri",
    calories: 42,
    protein: 3,
    carbs: 5,
    fat: 2,
    fiber: 0,
    allergens: ["Mjölk"],
    unit: "dl",
    inPantry: true,
    pantryAmount: 10,
  },
  {
    id: "5",
    name: "Laxfilé",
    category: "Fisk",
    calories: 208,
    protein: 25,
    carbs: 0,
    fat: 12,
    fiber: 0,
    allergens: ["Fisk"],
    unit: "g",
    inPantry: false,
  },
  {
    id: "6",
    name: "Potatis",
    category: "Grönsaker",
    calories: 77,
    protein: 2,
    carbs: 17,
    fat: 0,
    fiber: 2,
    allergens: [],
    unit: "g",
    inPantry: true,
    pantryAmount: 2000,
  },
  {
    id: "7",
    name: "Vispgrädde",
    category: "Mejeri",
    calories: 345,
    protein: 2,
    carbs: 3,
    fat: 36,
    fiber: 0,
    allergens: ["Mjölk"],
    unit: "dl",
    inPantry: true,
    pantryAmount: 5,
  },
  {
    id: "8",
    name: "Gul lök",
    category: "Grönsaker",
    calories: 40,
    protein: 1,
    carbs: 9,
    fat: 0,
    fiber: 2,
    allergens: [],
    unit: "st",
    inPantry: true,
    pantryAmount: 3,
  },
  {
    id: "9",
    name: "Smör",
    category: "Mejeri",
    calories: 717,
    protein: 1,
    carbs: 1,
    fat: 81,
    fiber: 0,
    allergens: ["Mjölk"],
    unit: "g",
    inPantry: true,
    pantryAmount: 250,
  },
  {
    id: "10",
    name: "Färsk dill",
    category: "Kryddor",
    calories: 43,
    protein: 3,
    carbs: 7,
    fat: 1,
    fiber: 2,
    allergens: [],
    unit: "dl",
    inPantry: false,
  },
]
